# Generated by Django 5.2 on 2025-04-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnikApp', '0002_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
