# Generated by Django 5.2 on 2025-04-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnikApp', '0003_alter_pedido_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='setor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
