# Generated by Django 5.2 on 2025-04-19 17:17

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnikApp', '0007_alter_mensagem_options_profile_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='fotos/'),
        ),
    ]
