# Generated by Django 5.2 on 2025-05-11 16:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnikApp', '0008_alter_profile_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='setor',
        ),
        migrations.AddField(
            model_name='pedido',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='fotos-produtos/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Suporte', 'Suporte')], default='Compra', max_length=10),
            preserve_default=False,
        ),
    ]
